apiVersion: v1
kind: Service
metadata:
    name: "test-f77a"
    labels:
        app: "test-f77a"
spec:
    type: LoadBalancer
    ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    selector:
        app: "test-f77a"